spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/world?serverTimezone=GMT&useUnicode=true&characterEncoding=utf8
    driver-class-name: com.mysql.cj.jdbc.Driver