spring:
  datasource:
    url: jdbc:mysql://localhost:3306/study?serverTimezone=GMT&useUnicode=true&characterEncoding=utf8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
      hibernata:
        #更新或者创建数据表结构
        ddl-auto: update
        #控制台显示SQL
        show-sql: true